### ISSUE TITLE
Authentication Failed/Tunnelling

### ISSUE THREAD

**Issue by idkjs** [sheharyarn/mongo-sync#17]
I have this admin user. When i run `./mongo-sync push`, i get an authentication error below.

I just spent a few hours trying to get through this figuring I would learn something. Anything obvious happening here? 

The reference line of code seems to refer to the tunneling. Is that necessary? If so, any docs you can point me to on how to make that happen?

Thank you.

Error:
```sh
mongo-sync:
-----------
Are you sure you want to push? Enter 'yes': yes
load_configs
Parsing 'config.yml'...
Success!

Dumping Local DB to /tmp/relayql/dump...
2017-06-03T20:47:01.454+0200    Failed: error connecting to db server: server returned error
 on SASL authentication step: Authentication failed.
Error on or near line 203; exiting with status 1
```

```bsh
MongoDB Enterprise > db.getUsers()
[
	{
		"_id" : "admin.admin",
		"user" : "admin",
		"db" : "admin",
		"roles" : [
			{
				"role" : "readWrite",
				"db" : "relayql"
			},
			{
				"role" : "read",
				"db" : "relayql"
			},
			{
				"role" : "dbOwner",
				"db" : "relayql"
			},
			{
				"role" : "userAdmin",
				"db" : "relayql"
			},
			{
				"role" : "changeOwnPasswordCustomDataRole",
				"db" : "admin"
			},
			{
				"role" : "root",
				"db" : "admin"
			},
			{
				"role" : "dbOwner",
				"db" : "admin"
			},
			{
				"role" : "dbAdmin",
				"db" : "relayql"
			},
			{
				"role" : "backup",
				"db" : "admin"
			},
			{
				"role" : "userAdminAnyDatabase",
				"db" : "admin"
			}
		],
		"customData" : {
			"title" : "Enso"
		}
	}
]
```

**Comment by sheharyarn** [comment]
This doesn't really look like an issue with the project, because `mongo-sync` doesn't support `SASL` or any other authentication or tunneling by design (other than SSH, which is still not perfect). It's written only as a convenience wrapper around `mongodump` and `mongorestore` (and honestly I don't know enough about MongoDB Enterprise or SASL to help you on that front either).

I suggest you read more on how authentication on MongoDB Enterprise works, and fork and modify `mongo-sync` to connect with it. Sorry that I can't be of more help.
