### ISSUE TITLE
Add support for including / excluding collections

### ISSUE THREAD

**Issue by elyas-bhy** [sheharyarn/mongo-sync#5]
It would be useful to have an option (in the configuration file, as a command-line argument, or both) to specify which collections to include and/or exclude during the sync operation.

See [mongodump --excludeCollection](https://docs.mongodb.org/manual/reference/program/mongodump/#cmdoption--excludeCollection) option.

**Comment by sheharyarn** [comment]
Hmmm. I intended `mongo-sync` to be as straight-forward and painless as possible to use. To me, adding all the features of `mongodump` and `mongorestore` doesn't make sense since then there would be no point of this at all.

But it's still an interesting option to give to the users. I'm going to think about this a bit, and see if I would really like to have this feature.

**Comment by lkraider** [comment]
Tripped on this today, sync was not working because it was trying to copy `system.roles` and `system.users` which I did not have permissions to do. Ended up editing the script to add:

```
--excludeCollectionsWithPrefix system
```

Maybe a boolean option on the yaml to enable/disable `system` namespace sync would keep it simple while still adding value?

**Comment by sheharyarn** [comment]
Like I said before, I don't believe we need to make `mongo-sync` very complicated. It's just meant to be a simple wrapper around `mongodump` and `mongorestore`.
